<?php
return array(
	'title'      => esc_html__( 'Logo Setting', 'naxly' ),
	'id'         => 'logo_setting',
	'desc'       => '',
	'subsection' => false,
	'fields'     => array(
		array(
			'id'       => 'image_favicon',
			'type'     => 'media',
			'url'      => true,
			'title'    => esc_html__( 'Favicon', 'naxly' ),
			'subtitle' => esc_html__( 'Insert site favicon image', 'naxly' ),
			'default'  => array( 'url' => get_template_directory_uri() . '/assets/images/favicon.ico' ),
			//'required' => array( array( 'logo_type', 'equals', 'image' ) ),
		),
		array(
            'id' => 'normal_logo_show',
            'type' => 'switch',
            'title' => esc_html__('Enable Home One Logo', 'naxly'),
            'default' => true,
        ),
		array(
			'id'       => 'image_normal_logo',
			'type'     => 'media',
			'url'      => true,
			'title'    => esc_html__( 'Home one Logo', 'naxly' ),
			'subtitle' => esc_html__( 'Insert site Home One logo image', 'naxly' ),
			'default'  => array( 'url' => get_template_directory_uri() . '/assets/images/logo-6.png' ),
			'required' => array( 'normal_logo_show', '=', true ),
		),
		array(
			'id'       => 'normal_logo_dimension',
			'type'     => 'dimensions',
			'title'    => esc_html__( 'Home one Logo Dimentions', 'naxly' ),
			'subtitle' => esc_html__( 'Select Home one Logo Dimentions', 'naxly' ),
			'units'    => array( 'em', 'px', '%' ),
			'default'  => array( 'Width' => '', 'Height' => '' ),
			'required' => array( 'normal_logo_show', '=', true ),
		),
		array(
            'id' => 'normal_logo_show2',
            'type' => 'switch',
            'title' => esc_html__('Enable Home one Sticky Logo', 'naxly'),
            'default' => true,
        ),
		array(
			'id'       => 'image_normal_logo2',
			'type'     => 'media',
			'url'      => true,
			'title'    => esc_html__( 'Home One Sticky Logo', 'naxly' ),
			'subtitle' => esc_html__( 'Insert site Home One Sticky logo image', 'naxly' ),
			'default'  => array( 'url' => get_template_directory_uri() . '/assets/images/small-logo.png' ),
			'required' => array( 'normal_logo_show', '=', true ),
		),
		array(
			'id'       => 'normal_logo_dimension2',
			'type'     => 'dimensions',
			'title'    => esc_html__( 'Home One Sticky Logo Dimentions', 'naxly' ),
			'subtitle' => esc_html__( 'Select Sticky Logo Dimentions', 'naxly' ),
			'units'    => array( 'em', 'px', '%' ),
			'default'  => array( 'Width' => '', 'Height' => '' ),
			'required' => array( 'normal_logo_show', '=', true ),
		),
		array(
            'id' => 'normal_logo_show3',
            'type' => 'switch',
            'title' => esc_html__('Enable Mobile Logo', 'naxly'),
            'default' => true,
        ),
		array(
			'id'       => 'image_normal_logo3',
			'type'     => 'media',
			'url'      => true,
			'title'    => esc_html__( 'Mobile Logo', 'naxly' ),
			'subtitle' => esc_html__( 'Insert site Mobile logo image', 'naxly' ),
			'default'  => array( 'url' => get_template_directory_uri() . '/assets/images/logo.png' ),
			'required' => array( 'normal_logo_show', '=', true ),
		),
		array(
			'id'       => 'normal_logo_dimension3',
			'type'     => 'dimensions',
			'title'    => esc_html__( 'Mobile Logo Dimentions', 'naxly' ),
			'subtitle' => esc_html__( 'Select Mobile Logo Dimentions', 'naxly' ),
			'units'    => array( 'em', 'px', '%' ),
			'default'  => array( 'Width' => '', 'Height' => '' ),
			'required' => array( 'normal_logo_show', '=', true ),
		),
		array(
            'id' => 'normal_logo_show4',
            'type' => 'switch',
            'title' => esc_html__('Enable Home Two Logo', 'naxly'),
            'default' => true,
        ),
		array(
			'id'       => 'image_normal_logo4',
			'type'     => 'media',
			'url'      => true,
			'title'    => esc_html__( 'Home Two Logo', 'naxly' ),
			'subtitle' => esc_html__( 'Insert site Home Two logo image', 'naxly' ),
			'default'  => array( 'url' => get_template_directory_uri() . '/assets/images/logo-2.png' ),
			'required' => array( 'normal_logo_show', '=', true ),
		),
		array(
			'id'       => 'normal_logo_dimension4',
			'type'     => 'dimensions',
			'title'    => esc_html__( 'Home Two Logo Dimentions', 'naxly' ),
			'subtitle' => esc_html__( 'Select Home Two Logo Dimentions', 'naxly' ),
			'units'    => array( 'em', 'px', '%' ),
			'default'  => array( 'Width' => '', 'Height' => '' ),
			'required' => array( 'normal_logo_show', '=', true ),
		),
		array(
            'id' => 'normal_logo_show5',
            'type' => 'switch',
            'title' => esc_html__('Enable Home Two Stciky Logo', 'naxly'),
            'default' => true,
        ),
		array(
			'id'       => 'image_normal_logo5',
			'type'     => 'media',
			'url'      => true,
			'title'    => esc_html__( 'Home Two Stciky Logo', 'naxly' ),
			'subtitle' => esc_html__( 'Insert site Home Two Stciky logo image', 'naxly' ),
			'default'  => array( 'url' => get_template_directory_uri() . '/assets/images/small-logo-2.png' ),
			'required' => array( 'normal_logo_show', '=', true ),
		),
		array(
			'id'       => 'normal_logo_dimension5',
			'type'     => 'dimensions',
			'title'    => esc_html__( 'Home Two Stciky Logo Dimentions', 'naxly' ),
			'subtitle' => esc_html__( 'Select Home Two Stciky Logo Dimentions', 'naxly' ),
			'units'    => array( 'em', 'px', '%' ),
			'default'  => array( 'Width' => '', 'Height' => '' ),
			'required' => array( 'normal_logo_show', '=', true ),
		),
		array(
            'id' => 'normal_logo_show6',
            'type' => 'switch',
            'title' => esc_html__('Enable Home Three Logo', 'naxly'),
            'default' => true,
        ),
		array(
			'id'       => 'image_normal_logo6',
			'type'     => 'media',
			'url'      => true,
			'title'    => esc_html__( 'Home Three Logo', 'naxly' ),
			'subtitle' => esc_html__( 'Insert site Home Three logo image', 'naxly' ),
			'default'  => array( 'url' => get_template_directory_uri() . '/assets/images/logo-3.png' ),
			'required' => array( 'normal_logo_show', '=', true ),
		),
		array(
			'id'       => 'normal_logo_dimension6',
			'type'     => 'dimensions',
			'title'    => esc_html__( 'Home Three Logo Dimentions', 'naxly' ),
			'subtitle' => esc_html__( 'Select Home Three Logo Dimentions', 'naxly' ),
			'units'    => array( 'em', 'px', '%' ),
			'default'  => array( 'Width' => '', 'Height' => '' ),
			'required' => array( 'normal_logo_show', '=', true ),
		),
		array(
            'id' => 'normal_logo_show7',
            'type' => 'switch',
            'title' => esc_html__('Enable Home Three Stciky Logo', 'naxly'),
            'default' => true,
        ),
		array(
			'id'       => 'image_normal_logo7',
			'type'     => 'media',
			'url'      => true,
			'title'    => esc_html__( 'Home Three Stciky Logo', 'naxly' ),
			'subtitle' => esc_html__( 'Insert site Home Three Stciky logo image', 'naxly' ),
			'default'  => array( 'url' => get_template_directory_uri() . '/assets/images/small-logo-3.png' ),
			'required' => array( 'normal_logo_show', '=', true ),
		),
		array(
			'id'       => 'normal_logo_dimension7',
			'type'     => 'dimensions',
			'title'    => esc_html__( 'Home Three Stciky Logo Dimentions', 'naxly' ),
			'subtitle' => esc_html__( 'Select Home Three Stciky Logo Dimentions', 'naxly' ),
			'units'    => array( 'em', 'px', '%' ),
			'default'  => array( 'Width' => '', 'Height' => '' ),
			'required' => array( 'normal_logo_show', '=', true ),
		),
		array(
            'id' => 'normal_logo_show8',
            'type' => 'switch',
            'title' => esc_html__('Enable Home Four Logo', 'naxly'),
            'default' => true,
        ),
		array(
			'id'       => 'image_normal_logo8',
			'type'     => 'media',
			'url'      => true,
			'title'    => esc_html__( 'Home Four Logo', 'naxly' ),
			'subtitle' => esc_html__( 'Insert site Home Four logo image', 'naxly' ),
			'default'  => array( 'url' => get_template_directory_uri() . '/assets/images/logo-4.png' ),
			'required' => array( 'normal_logo_show', '=', true ),
		),
		array(
			'id'       => 'normal_logo_dimension8',
			'type'     => 'dimensions',
			'title'    => esc_html__( 'Home Four Logo Dimentions', 'naxly' ),
			'subtitle' => esc_html__( 'Select Home Four Logo Dimentions', 'naxly' ),
			'units'    => array( 'em', 'px', '%' ),
			'default'  => array( 'Width' => '', 'Height' => '' ),
			'required' => array( 'normal_logo_show', '=', true ),
		),
		array(
            'id' => 'normal_logo_show9',
            'type' => 'switch',
            'title' => esc_html__('Enable Home Four Stciky Logo', 'naxly'),
            'default' => true,
        ),
		array(
			'id'       => 'image_normal_logo9',
			'type'     => 'media',
			'url'      => true,
			'title'    => esc_html__( 'Home Four Stciky Logo', 'naxly' ),
			'subtitle' => esc_html__( 'Insert site Home Four Stciky logo image', 'naxly' ),
			'default'  => array( 'url' => get_template_directory_uri() . '/assets/images/small-logo-4.png' ),
			'required' => array( 'normal_logo_show', '=', true ),
		),
		array(
			'id'       => 'normal_logo_dimension9',
			'type'     => 'dimensions',
			'title'    => esc_html__( 'Home Four Stciky Logo Dimentions', 'naxly' ),
			'subtitle' => esc_html__( 'Select Home Four Stciky Logo Dimentions', 'naxly' ),
			'units'    => array( 'em', 'px', '%' ),
			'default'  => array( 'Width' => '', 'Height' => '' ),
			'required' => array( 'normal_logo_show', '=', true ),
		),
		array(
            'id' => 'normal_logo_show10',
            'type' => 'switch',
            'title' => esc_html__('Enable Home Five Logo', 'naxly'),
            'default' => true,
        ),
		array(
			'id'       => 'image_normal_logo10',
			'type'     => 'media',
			'url'      => true,
			'title'    => esc_html__( 'Home Five Logo', 'naxly' ),
			'subtitle' => esc_html__( 'Insert site Home Five logo image', 'naxly' ),
			'default'  => array( 'url' => get_template_directory_uri() . '/assets/images/logo-5.png' ),
			'required' => array( 'normal_logo_show', '=', true ),
		),
		array(
			'id'       => 'normal_logo_dimension10',
			'type'     => 'dimensions',
			'title'    => esc_html__( 'Home Five Logo Dimentions', 'naxly' ),
			'subtitle' => esc_html__( 'Select Home Five Logo Dimentions', 'naxly' ),
			'units'    => array( 'em', 'px', '%' ),
			'default'  => array( 'Width' => '', 'Height' => '' ),
			'required' => array( 'normal_logo_show', '=', true ),
		),
		array(
            'id' => 'normal_logo_show11',
            'type' => 'switch',
            'title' => esc_html__('Enable Home Five Stciky Logo', 'naxly'),
            'default' => true,
        ),
		array(
			'id'       => 'image_normal_logo11',
			'type'     => 'media',
			'url'      => true,
			'title'    => esc_html__( 'Home Five Stciky Logo', 'naxly' ),
			'subtitle' => esc_html__( 'Insert site Home Five Stciky logo image', 'naxly' ),
			'default'  => array( 'url' => get_template_directory_uri() . '/assets/images/small-logo-5.png' ),
			'required' => array( 'normal_logo_show', '=', true ),
		),
		array(
			'id'       => 'normal_logo_dimension11',
			'type'     => 'dimensions',
			'title'    => esc_html__( 'Home Five Stciky Logo Dimentions', 'naxly' ),
			'subtitle' => esc_html__( 'Select Home Five Stciky Logo Dimentions', 'naxly' ),
			'units'    => array( 'em', 'px', '%' ),
			'default'  => array( 'Width' => '', 'Height' => '' ),
			'required' => array( 'normal_logo_show', '=', true ),
		),
		array(
            'id' => 'normal_logo_show12',
            'type' => 'switch',
            'title' => esc_html__('Enable Inner Page Logo', 'naxly'),
            'default' => true,
        ),
		array(
			'id'       => 'image_normal_logo12',
			'type'     => 'media',
			'url'      => true,
			'title'    => esc_html__( 'Inner Page Logo', 'naxly' ),
			'subtitle' => esc_html__( 'Insert site Inner Page logo image', 'naxly' ),
			'default'  => array( 'url' => get_template_directory_uri() . '/assets/images/logo.png' ),
			'required' => array( 'normal_logo_show', '=', true ),
		),
		array(
			'id'       => 'normal_logo_dimension12',
			'type'     => 'dimensions',
			'title'    => esc_html__( 'Inner Page Logo Dimentions', 'naxly' ),
			'subtitle' => esc_html__( 'Select Inner Page Logo Dimentions', 'naxly' ),
			'units'    => array( 'em', 'px', '%' ),
			'default'  => array( 'Width' => '', 'Height' => '' ),
			'required' => array( 'normal_logo_show', '=', true ),
		),
		array(
            'id' => 'normal_logo_show13',
            'type' => 'switch',
            'title' => esc_html__('Enable Inner Page Stciky Logo', 'naxly'),
            'default' => true,
        ),
		array(
			'id'       => 'image_normal_logo13',
			'type'     => 'media',
			'url'      => true,
			'title'    => esc_html__( 'Inner Page Stciky Logo', 'naxly' ),
			'subtitle' => esc_html__( 'Insert site Inner Page Stciky logo image', 'naxly' ),
			'default'  => array( 'url' => get_template_directory_uri() . '/assets/images/small-logo.png' ),
			'required' => array( 'normal_logo_show', '=', true ),
		),
		array(
			'id'       => 'normal_logo_dimension13',
			'type'     => 'dimensions',
			'title'    => esc_html__( 'Inner Page Stciky Logo Dimentions', 'naxly' ),
			'subtitle' => esc_html__( 'Select Inner Page Stciky Logo Dimentions', 'naxly' ),
			'units'    => array( 'em', 'px', '%' ),
			'default'  => array( 'Width' => '', 'Height' => '' ),
			'required' => array( 'normal_logo_show', '=', true ),
		),
		array(
			'id'       => 'logo_settings_section_end',
			'type'     => 'section',
			'indent'      => false,
		),
	),
);
